---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      containers:
      - name: notificationservice
        image: pitstop/notificationservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        
        
         

            
