---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: rabbitmq
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  serviceName: rabbitmq
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          env:
            - name: RABBITMQ_CONFIG_FILE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq.conf
                  key: RABBITMQ_CONFIG_FILE 
          ports:
            - containerPort: 15672
            - containerPort: 5672
          volumeMounts:
            - name: rabbitmqdata
              mountPath: /var/lib/rabbitmq:/etc/pitstop/
              readOnly: false
      volumes: 
        - name: rabbitmqdata
          configMap: 
            name: rabbitmq.conf
  volumeClaimTemplates:
    - metadata:
        name: rabbitmqdata
      spec:
        resources:
          requests:
            storage: "4Gi"
        storageClassName: managed-csi
        accessModes:
          - ReadWriteOnce
    

---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: rabbitmq.conf
data:
  RABBITMQ_CONFIG_FILE: /etc/pitstop/rabbitmq.conf
---
apiVersion: v1 
kind: Service 
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbit
  type: NodePort
  ports:
    - name: rabbit-1
      port: 15672 
      targetPort: 15672
      nodePort: 30001
    - name: rabbit-2
      port: 5672
      targetPort: 5672
      nodePort: 30002
     
---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: sq-conf
data:
  ACCEPT_EULA: "Y"
  MSSQL_PID: Developer
  SA_PASSWORD: 8jkGh47hnDw89Haq8LN2
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: sqlserver
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: sql
  serviceName: sqlserver
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/azure-sql-edge
          env:
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: sq-conf
                  key: ACCEPT_EULA 
            - name: MSSQL_PID
              valueFrom:
                configMapKeyRef:
                  name: sq-conf
                  key: MSSQL_PID 
            - name: SA_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sq-conf
                  key: SA_PASSWORD  
          ports:
            - containerPort: 1433
            - containerPort: 1434
          volumeMounts:
            - name: sqlserverdata
              mountPath: /var/opt/mssql
              readOnly: false
      volumes: 
        - name: sqlserverdata
          configMap: 
            name: sq-conf
  volumeClaimTemplates:
    - metadata:
        name: sqlserverdata
      spec:
        resources:
          requests:
            storage: "4Gi"
        storageClassName: managed-csi
        accessModes:
          - ReadWriteOnce

---
apiVersion: v1 
kind: Service 
metadata:
  name: sqlserver
spec:
  selector:
    app: sql
  type: NodePort
  ports:
    - port: 1434
      targetPort: 1433
      nodePort: 31111
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: mail
  template:
    metadata:
      labels:
        app: mail
    spec:
      containers:
      - name: mailserver
        image: maildev/maildev:1.1.0
        ports:
        - containerPort: 25
        - containerPort: 4000
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-3
spec:
  selector:
    app: mail
  type: ClusterIP
  ports: 
    - name: svc1
      port: 25
      targetPort: 25
    - name: svc2
      port: 4000
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-server
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: log 
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
      - name: logserver
        image: datalust/seq:latest
        ports:
          - containerPort: 5341
          - containerPort: 80
        env:
        - name: ACCEPT_EULA
          value: "Y" 
---
apiVersion: v1
kind: Service
metadata:
  name: svc-4
spec:
  selector:
    app: log
  type: ClusterIP
  ports: 
    - name: svc1
      port: 5341
      targetPort: 5431
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-mngmt
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: veh
  template:
    metadata:
      labels:
        app: veh
    spec:
      containers:
      - name: vehiclemanagementapi
        image: pitstop/vehiclemanagementapi:1.0
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu: "512m"
            memory: "1024Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production 
--- 
apiVersion: v1
kind: Service
metadata:
  name: vehiclemanagementapi
spec:
  selector:
    app: veh 
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-mngmt
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: customermanagementapi
        image: pitstop/customermanagementapi:1.0
        ports:
          - containerPort: 5100
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production 
--- 
apiVersion: v1
kind: Service
metadata:
  name: customermanagementapi
spec:
  selector:
    app: custom
  type: NodePort
  ports:
    - port: 5100
      targetPort: 5100
      nodePort: 31155
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: work
  template:
    metadata:
      labels:
        app: work
    spec:
      containers:
      - name: workshopmanagementapi
        image: pitstop/workshopmanagementapi:1.0
        ports:
          - containerPort: 5200
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        resources:
          limits: 
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"
--- 
apiVersion: v1
kind: Service
metadata:
  name: workshopmanagementapi
spec:
  selector:
    app: work
  type: ClusterIP
  ports:
    - port: 5200
      targetPort: 5200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditlogservice
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
      - name: auditlogservice 
        image: pitstop/auditlogservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        resources:
          limits: 
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceservice
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: invoice
  template:
    metadata:
      labels:
        app: invoice
    spec:
      containers:
      - name: invoiceservice
        image: pitstop/invoiceservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        resources:
          limits: 
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      containers:
      - name: notificationservice
        image: pitstop/notificationservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        resources:
          limits: 
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeservice
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: timeservice
  template:
    metadata:
      labels:
        app: timeservice
    spec:
      containers:
      - name: timeservice
        image: pitstop/timeservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        resources:
          limits: 
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshopmanagementeventhandler
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: event 
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
      - name: workshopmanagementeventhandler
        image: pitstop/workshopmanagementeventhandler:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        resources:
          limits: 
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports: 
    - port: 7005
      targetPort: 7005
      nodePort: 31542
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: webapp 
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: pitstop/webapp:1.0
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        ports:
          - containerPort: 7005
        resources:
          limits: 
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"
       
        
        
         

            


  


    
      
        
        
         

            
       
        
        
         

            

     
        
        
         

            

       
        
        
         

            
    

  

        
        
        
         

            

  

        
        
        
         

            
     

  

       
        
        
         

            


    
    


    
        
            


    

    
       


    

    


      



 

      