--- 
apiVersion: v1
kind: Service
metadata:
  name: customermanagementapi
spec:
  selector:
    app: custom
  type: NodePort
  ports:
    - port: 5100
      targetPort: 5100
      nodePort: 31155

  

 