---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditlogservice
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
      - name: auditlogservice 
        image: pitstop/auditlogservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        resources:
          limits: 
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"
       
        
        
         

            
