apiVersion: v1
kind: Service
metadata:
  name: svc-3
spec:
  selector:
    app: mail
  type: ClusterIP
  ports: 
    - name: svc1
      port: 25
      targetPort: 25
    - name: svc2
      port: 4000
      targetPort: 80
     


    
