---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-mngmt
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: veh
  template:
    metadata:
      labels:
        app: veh
    spec:
      containers:
      - name: vehiclemanagementapi
        image: pitstop/vehiclemanagementapi:1.0
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu: "512m"
            memory: "1024Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production 
       
        
        
         

            
