---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: work
  template:
    metadata:
      labels:
        app: work
    spec:
      containers:
      - name: workshopmanagementapi:1.0
        image: pitstop/workshopmanagementapi:1.0
        ports:
          - containerPort: 5200
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
       
        
        
         

            
