---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeservice
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: timeservice
  template:
    metadata:
      labels:
        app: timeservice
    spec:
      containers:
      - name: timeservice
        image: pitstop/timeservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        
       
        
        
         

            
