     
---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: sq-conf
data:
  ACCEPT_EULA: "Y"
  MSSQL_PID: Developer
  SA_PASSWORD: 8jkGh47hnDw89Haq8LN2
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: sqlserver
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: sql
  serviceName: sqlserver
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/azure-sql-edge
          env:
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: sq-conf
                  key: ACCEPT_EULA 
            - name: MSSQL_PID
              valueFrom:
                configMapKeyRef:
                  name: sq-conf
                  key: MSSQL_PID 
            - name: SA_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sq-conf
                  key: SA_PASSWORD  
          ports:
            - containerPort: 1433
            - containerPort: 1434
          volumeMounts:
            - name: sqlserverdata
              mountPath: /var/opt/mssql
              readOnly: false
      volumes: 
        - name: sqlserverdata
          configMap: 
            name: sq-conf
 

---
apiVersion: v1 
kind: Service 
metadata:
  name: sqlserver
spec:
  selector:
    app: sql
  type: NodePort
  ports:
    - port: 1434
      targetPort: 1433
      nodePort: 31111
    
       


    

    


      



 
